openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts Application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Documentation of the application "Contacts"
tags:
  - name: Contacts
    description: Operations about Contacts
  - name: Auth
    description: Operations about Auth
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-893g.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/registerPost.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/loginPost.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refreshPost.yaml'
  /auth/send-reset-email:
    post:
      $ref: '../swagger/paths/auth/sendResetEmailPost.yaml'
  /auth/reset-pwd:
    post:
      $ref: '../swagger/paths/auth/resetPwdPost.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
