openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts aplocation
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Documentation of the application "Contacts"
tags:
  - name: Contacts
    description: Operations about Contacts
  - name: Auth
    description: Operations about Auth
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-893g.onrender.com
paths:
  # тут будуть посилання на ендпоінти
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
